# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expand_hclust_cells_cpp <- function(edge_c, edge_len_c, tip_ids_old, cells_by_cluster, tip_edge_len = 0.0) {
    .Call(`_numbatmod_expand_hclust_cells_cpp`, edge_c, edge_len_c, tip_ids_old, cells_by_cluster, tip_edge_len)
}

roman2int_internal <- function(letters, nchar) {
    .Call(`_numbatmod_roman2int_internal`, letters, nchar)
}

CgetQ <- function(logQ, children_dict, node_order) {
    .Call(`_numbatmod_CgetQ`, logQ, children_dict, node_order)
}

allChildrenCPP <- function(E) {
    .Call(`_numbatmod_allChildrenCPP`, E)
}

